linters:
  disable-all: true
  enable:
    - deadcode
    - goconst
    - gocritic
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - varcheck