linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - deadcode
    - decorder
    - depguard
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - gocheckcompilerdirectives
    - gochecknoinits
    - ginkgolinter
    - goconst
    - gocritic
    - godot
    - goerr113
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck