name: unittests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  devopstest:
    runs-on: ubuntu-latest
    container: golang:1.19

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: go test -race -tags fast -coverprofile unit.txt -covermode atomic ./...
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./unit.txt
          flags: unit
          name: unit